name: 'Create and test rego'
description: 'Placeholder'
inputs:
  output-rego-file-path:
    description: 'Output rego file path'
    required: true
  rego-policy-folder:
    description: 'Rego policies folder'
    required: false
  rego-tests-folder:
    description: 'Rego tests folder'
    required: false
runs:
  using: "composite"
  steps:
    - name: "Print something"
      id: psomething
      shell: bash
      run: |
        mkdir ./tmp
        echo "echo ls"
        ls
        echo "echo ls ${{ inputs.rego-policy-folder }} {{ inputs.rego-policy-folder }}"
        ls ${{ inputs.rego-policy-folder }}
        cat ${{ inputs.rego-policy-folder }}/*rego > ./tmp/rules.rego
        echo "echo rules.rego"
        echo ./tmp/rules.rego
        cat ${{ inputs.rego-tests-folder }}/*rego > ./tmp/tests/tests.rego
        cat ./tmp/rules.rego > ${{ inputs.output-rego-file-path }}
        echo "echo ls"
        ls
        rm -rf ./tmp
        