# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo "test" > ./"$(date +"%Y_%m_%d_%I_%M_%p").log"
          git config --global user.name ${{ secrets.GH_USER }}
          git config --global user.email "${{ secrets.GH_MAIL }}"
          git add --a
          git commit -m "test commit"
          git push origin main
